version: "3"

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  server:
    image: nestjs-sequelize
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    environment:
      NODE_ENV: development
      HOST: "0.0.0.0"
      PORT: 3000
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      JWT_SECRET_KEY: keyboard_cat
    depends_on:
      - postgres
    links:
      - postgres

